### ISSUE TITLE
Fix compatibility with Logstash V5

### ISSUE THREAD

**Issue by catalinvr** [Heiko-san/logstash-input-s3sqs#3]
Hi @Heiko-san 

Can you merge the #2 pull request?

Thanks
Catalin

**Comment by maxstepanov** [comment]
Would be nice to get it merged.
This plugin can't be installed on v5 currently

**Comment by wintergren** [comment]
@Heiko-san any plan on merging this anytime soon? ...

**Comment by Heiko-san** [comment]
I did the merge.
But release wont work again, although I documented each step I took last time...
This is crazy, I never saw a language where deploying a package is such a pain...
Is there a way to write logstash plugins in any reasonable language? I will happily port the code.
